export const GRID_WIDTH = 100;
export const GRID_HEIGHT = 72;
export const CELL_SIZE = 10;

export const TICK_MS = 80;
export const STARTING_LIVES = 3;

export const DIRECTIONS = {
  UP: "UP",
  RIGHT: "RIGHT",
  DOWN: "DOWN",
  LEFT: "LEFT",
};

export const DIRECTION_VECTORS = {
  [DIRECTIONS.UP]: { x: 0, y: -1 },
  [DIRECTIONS.RIGHT]: { x: 1, y: 0 },
  [DIRECTIONS.DOWN]: { x: 0, y: 1 },
  [DIRECTIONS.LEFT]: { x: -1, y: 0 },
};

export const LEFT_TURN = {
  [DIRECTIONS.UP]: DIRECTIONS.LEFT,
  [DIRECTIONS.LEFT]: DIRECTIONS.DOWN,
  [DIRECTIONS.DOWN]: DIRECTIONS.RIGHT,
  [DIRECTIONS.RIGHT]: DIRECTIONS.UP,
};

export const RIGHT_TURN = {
  [DIRECTIONS.UP]: DIRECTIONS.RIGHT,
  [DIRECTIONS.RIGHT]: DIRECTIONS.DOWN,
  [DIRECTIONS.DOWN]: DIRECTIONS.LEFT,
  [DIRECTIONS.LEFT]: DIRECTIONS.UP,
};

export const OPPOSITE_DIRECTION = {
  [DIRECTIONS.UP]: DIRECTIONS.DOWN,
  [DIRECTIONS.DOWN]: DIRECTIONS.UP,
  [DIRECTIONS.LEFT]: DIRECTIONS.RIGHT,
  [DIRECTIONS.RIGHT]: DIRECTIONS.LEFT,
};

export const PLAYER_COLORS = {
  1: "#00f7ff",
  2: "#ff8c00",
};
