services:
  postgres:
    image: postgres:16
    container_name: transcendence_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d
    networks:
      - transcendence

  nginx:
    build:
      context: ./backend/nginx
      args:
        HOST_NAME: ${HOST_NAME-localhost}
    ports:
      - "8443:443"
    depends_on:
      - frontend
      - gateway
      - users
      - chat
    networks:
      - transcendence

  chat:
    build: ./backend/micro_services/chat-service
    restart: on-failure
    environment:
      #connect to postgres container using service name as hostname
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      #shared JWT secret (from .env), must match the value used by all other services
      JWT_SECRET: ${JWT_ACCESS_SECRET}
      FRONTEND_URL: ${FRONTEND_URL:-https://localhost:8443}
    depends_on:
      - postgres
    networks:
      - transcendence

  users:
    build: ./backend/micro_services/users
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      SEED_PASSWORD_FEMORENO: ${SEED_PASSWORD_FEMORENO}
      SEED_PASSWORD_PROSAS: ${SEED_PASSWORD_PROSAS}
      SEED_PASSWORD_AAMOROS: ${SEED_PASSWORD_AAMOROS}
      SEED_PASSWORD_MZULOAGA: ${SEED_PASSWORD_MZULOAGA}
      SEED_PASSWORD_JOTRUJIL: ${SEED_PASSWORD_JOTRUJIL}
    networks:
      - transcendence
    depends_on:
      - postgres

  gateway:
    build: ./backend/gateway
    depends_on:
      - users
      - postgres
    environment:
      CHAT_SERVICE: http://chat:3003
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    networks:
      - transcendence

  game:
    build: ./backend/micro_services/game
    environment:
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
    networks:
      - transcendence
    depends_on:
      - postgres
      - users

  frontend:
    build: ./frontend
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - transcendence
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  transcendence:
    driver: bridge
