services:
  postgres:
    image: postgres:16
    container_name: transcendence_postgres
    restart: always
    environment:
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: transcendence
      POSTGRES_DB: transcendence
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - transcendence

  nginx:
    build:
      context: ./backend/nginx
      args:
        HOST_NAME: ${HOST_NAME-localhost}
    ports:
      - "8443:443"
    depends_on:
      - frontend
      - gateway
      - users
    networks:
      - transcendence

  users:
    build: ./backend/micro_services/users
    networks:
      - transcendence
    depends_on:
      - postgres

  gateway:
    build: ./backend/gateway
    depends_on:
      - users
      - postgres
    networks:
      - transcendence

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - transcendence
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  transcendence:
    driver: bridge
