events {}

http {
    # Load a file than map extensions of files like .html
    include mime.types;
    # B plan if not find mime type, treat the files as generic binaries
    default_type application/octet-stream; 

    # Define a virtual server
    server {
        #listen 443
        listen 443 ssl;
        #select which server use where there is multiple domain
        server_name localhost;

        #present the certificate
        ssl_certificate /etc/ssl/certs/server.crt;
        ssl_certificate_key /etc/ssl/private/server.key;

        #define the protocols (block tls 1.0 and 1.1)
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        #use a high ciphers and reject null ciphers
        ssl_ciphers HIGH:!aNULL:!MD5;

        # API → gateway
        location /api/ {
            proxy_pass http://gateway:3000/;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Chat WebSocket → chat-service directly (gateway can't proxy WebSockets)
        location /socket.io/ {
            proxy_pass http://chat:3003;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header Authorization $http_authorization;
        }

        # Frontend
        location / {
            proxy_pass http://frontend:5173;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
